### ISSUE TITLE
[Bug fix][FE] 前端页面缺失版本核验信息

### ISSUE THREAD

**Issue by Tz-H** [anwen/ccnft-demo#2]
这是一个 Bug Fix 问题提交测试报告，但它也包含了一个真实需要解决的问题：项目当前的前端页面缺失一个非常重要的开发元素：版本及版本核验信息，这会导致所有的问题提交以及问题的修复无法及时了解它所针对的版本信息，也因此无法对问题的修复加以核验和追溯。

## 问题重现步骤

1. 打开项目网站 https://ccnft-test.dweb-lab.com/
2. 查验网站网页上的项目版本信息情况
     ##### 期待结果：
     网站网页上可以查询到项目版本信息情况
     ##### 实际结果：
     网站网页上上没有项目版本信息情况

### 附加信息/建议：

1. 版本号要与后台项目更新发布的版本相一致
2. 版本号要针对不同的模块，前台后台要分别设置，不要混在一起，例如：
    - 「后台服务版本 backend」：v0.0.1
    - 「前台网页版本 frontend」：v0.2.3
 3. 当版本进行升级后，要说清楚这个版本改动是解决/修复了哪些问题，或者提供了哪些新的功能
 4. 任何改动，都提供一个版本升级，不用担心版本升级太多太快

## 截图

![2021-12-29_19-12-54](https://user-images.githubusercontent.com/1928161/147696692-0d06c899-06ec-4f6c-9d89-7faed9d9a2fe.png)

**Comment by askender** [comment]
v0.4.4   fix post api and title render and add version on pages
Please if the bug(UX) is fixed.

**Comment by askender** [comment]
Maybe we can add  web2 backend version here too. 
and web3 blockchain we are using.

**Comment by Tz-H** [comment]
> v0.4.4 fix post api and title render and add version on pages Please check if the bug (UX problem) is fixed.

Yes, please close this issue and quote like this to clearly claim that on which version this bug has been fixed, e.g.

> "Fixed it at Frontend version v0.4.4, bug closed"

I'll then check the closed issue based the version info given and will mark it as "VERIFIED" if the bug is fixed indeed, or reopen the issue if the bug is still reproducible.

**Comment by Tz-H** [comment]
@askender 

As please add me into this project so that I could add/modify the Labels and Milestones to offer a better development / management environment.

**Comment by askender** [comment]
Fixed it at Frontend Version: v0.4.4+6cfade1   Backend Version: v0.2.1+f931d21      Close this issue.

**Comment by Tz-H** [comment]
VERIFIED

FE version `v0.4.4+6cfade1`

**Comment by Tz-H** [comment]
@askender 

Please note that the role of `assignee` should be the people who develops/fixes the issue, not the people who reports the issue.
