### ISSUE TITLE
[Bug] content of `My Articles` not show because of a Metamask problem

### ISSUE THREAD

**Issue by askender** [anwen/ccnft-demo#3]
## Background info
https://github.com/MetaMask/metamask-extension/issues/10671

### fix(hack) in frontend
```
const { utils } = require('ethers');
const address = '0x63c4393693af799109df135be8afb8044ba0a581';
utils.getAddress(address);
'0x63c4393693aF799109Df135be8afb8044BA0A581'
```

### lowercase in backend
- we still need a backend for fast retrieval the caches for now

**Comment by askender** [comment]
We will choose solution2: lowercase in backend as a quick fix.
We will follow EIP-55 better in the future.

**Comment by askender** [comment]
fixed.

**Comment by Tz-H** [comment]
@askender 

Reopen this issue as I cannot check and verify it based on its description.

Please provide the following necessary info:

1. The bug reproduce steps
2. What's the expected result 
3. What's the actual result

For example:

## 问题复现步骤

1. 打开网站 https://ccnft-test.dweb-lab.com/
2. 点击 [My Articles] 选项
3. 检查 [MyArticles] 页面内容
   ##### 期待结果：
   [My Articles] 页面内容可以正常显示
   ##### 实际结果：
   [My Articles] 页面内容无法显示

**Comment by askender** [comment]
Thanks,  you described it for me.  
As this is a bug found by me and solved by me, I'm lazy somethimes.

嗯，在严谨和高效中取得平衡很难，
如果有模板，我会更容易遵守规范一些， 
类似这个： https://github.com/filecoin-project/lotus/issues/new/choose

**Comment by Tz-H** [comment]
> 嗯，在严谨和高效中取得平衡很难，
> 如果有模板，我会更容易遵守规范一些，

唯一需要补充并确认的一点就是，Issue 的描述要有问题复现步骤和复核手段（需要检查的，预期的结果是什么），这样除了开发人员来调查解决问题并 close issue，可以有另外一个人可以根据问题的描述来核对问题是否已经真正解决并添加`VERIFIED`标签进行标记。

**Comment by askender** [comment]
嗯，理论上是这样的。
一般来说，提问人 = 确认者，刚好这个我也是顺手修复的开发者，都是同一个人的时候难免偷懒。

我在https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+author%3Aaskender+    提的issue都遵守了模板要求， 人还是需要技术辅助协助的，但靠自制力不够。

**Comment by askender** [comment]
close it.  Hope we can find all bugs and make it better.

**Comment by Tz-H** [comment]
VERIFIED.

FE version is `v0.4.4+6cfade1`
